# Daya Tampung

Daya tampung Universitas Sultan Ageng Tirtayasa untuk program D3 dan S1

## Tahun Akademik 2019/2020

```{r, echo=FALSE, message=FALSE, warning=FALSE}
dt <- read.csv("static/dt.csv")
dt19 <- dt[dt$TA == 2019, 1:4]
names(dt19) <- c("Program Studi", "SNMPTN", "SBMPTN", "SMMPTN")
library(janitor)
library(kableExtra)
dt19 <- adorn_totals(dt19, where = c("row", "col"), name = "Total")
kable(dt19, row.names = F) %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                latex_options = "scale_down") %>%
  add_header_above(c(" " = 1, "Jalur Masuk" = 3, " " = 1)) %>%
  pack_rows("Hukum", 1, 1, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Keguruan dan Ilmu Pendidikan", 2, 20, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Teknik", 21, 26, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Pertanian", 27, 31, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ekonomi dan Bisnis", 32, 35, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ilmu Sosial dan Ilmu Politik", 36, 38, label_row_css = "background-color: #666; color: #fff;")

```


## Tahun Akademik 2020/2021

```{r, echo=FALSE, message=FALSE, warning=FALSE}
dt20 <- dt[dt$TA == 2020, 1:4]
names(dt20) <- c("Program Studi", "SNMPTN", "SBMPTN", "SMMPTN")
dt20 <- adorn_totals(dt20, where = c("row", "col"), name = "Total")
kable(dt20, row.names = F) %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                latex_options = "scale_down") %>%
  add_header_above(c(" " = 1, "Jalur Masuk" = 3, " " = 1)) %>%
  pack_rows("Hukum", 1, 1, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Keguruan dan Ilmu Pendidikan", 2, 19, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Teknik", 20, 25, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Pertanian", 26, 29, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ekonomi dan Bisnis", 30, 33, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ilmu Sosial dan Ilmu Politik", 34, 36, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Kedokteran", 37, 39, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("D3", 40, 44, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Pascasarjana", 45, 56, label_row_css = "background-color: #666; color: #fff;")

```