# Rekapitulasi SDM

> Sebaran SDM berdasarkan jenis kelamin

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
library(janitor)
library(kableExtra)
sdm <- read.csv("static/SDM.csv")
sdm$STATUS <- factor(sdm$STATUS, levels = c("Dosen PNS", "Dosen TKK",
                                            "Tendik PNS", "Tendik Non PNS"))

sd <- sdm %>%
  group_by(JK) %>%
  summarize(banyak = n())
sd$JK <- c("Laki-Laki", "Perempuan")

div(plot_ly(type = "pie", labels = sd$JK, values = sd$banyak,
        textinfo = "label+percent",
        insidetextorientation = "radial"), align = "center")

sd <- sdm %>%
  group_by(STATUS, JK) %>%
  summarize(total = n())
sd <- sd %>%
  pivot_wider(names_from = JK, values_from = total)
names(sd) <- c("SDM", "Laki-Laki", "Perempuan")
sd$SDM <- c("Dosen PNS", "Dosen Non PNS", "Tendik PNS", "Tendik Non PNS")

sd$SDM <- factor(sd$SDM, levels = sd[["SDM"]])

div(plot_ly(sd, x = ~SDM, y = ~`Laki-Laki`, type = 'bar', name = "Laki-Laki") %>% 
      add_trace(y = ~Perempuan, name = "Perempuan") %>%
      layout(yaxis = list(title = ' '), barmode = 'group'), align = "center")
```

> Sebaran SDM berdasarkan tingkat pendidikan

```{r, echo=FALSE, message=FALSE, warning=FALSE}
sd <- sdm %>%
  group_by(PENDIDIKAN, STATUS) %>%
  summarize(total = n())
sd <- sd %>%
  pivot_wider(names_from = STATUS, values_from = total)
sd[is.na(sd)] <- 0
sd$PENDIDIKAN <- c("S3", "S2", "Spesialis", "S1 Profesi", "S1",
                   "Diploma", "SLTA", "SLTP", "SD")
sd <- adorn_totals(sd, where = c("row", "col"), name = "Jumlah")
kable(sd) %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                latex_options = "scale_down") %>%
  add_header_above(c(" " = 1, "SDM" = 4, " " = 1))
```

